version: "3.8"
services:
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    labels:
      NAME: "rabbitmq1"
  stp2glb:
    image: balbatross/cae-stp2glb
    build: ./step2glb
    depends_on:
      - rabbit1
    volumes:
      - "/home/ubuntu/efs/:/data/cae"
  glb2glb:
    image: balbatross/cae-glb2glb
    build: ./glb2glb
    depends_on:
      - rabbit1
    volumes:
      - "/home/ubuntu/efs/:/data/cae"
  gltfpack:
    image: balbatross/cae-gltfpack
    depends_on:
      - rabbit1
    volumes:
      - "/home/ubuntu/efs/:/data/cae"

